version: '3'
services:

  worker1:
    build: ./Worker
    restart: always
    container_name: worker1
    ports:
      - "8081:8081"
  worker2:
    build: ./Worker
    restart: always
    container_name: worker2
    ports:
      - "8082:8081"
  worker3:
    build: ./Worker
    restart: always
    container_name: worker3
    ports:
      - "8083:8081"

  bootstrap:
    build: ./Bootstrap
    restart: always
    container_name: bootstrap
    ports:
      - "8080:8080"
    depends_on:
      - worker1
      - worker2
      - worker3
